# -- general -------------------------------------------------------------------

set -g default-terminal "tmux-256color"
set -sa terminal-overrides ",xterm*:Tc"   # true color support
set -g history-limit 10000
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g set-clipboard on
set -sg escape-time 0                     # no delay after pressing Escape

# -- pane & window creation ----------------------------------------------------

bind '"' split-window -v -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"
bind 'c' new-window -c "#{pane_current_path}"
